#! /bin/bash

# programming
bspc config -m $BSPWM_EXTERNALMONITOR -d programming left_padding 600
bspc config -m $BSPWM_EXTERNALMONITOR -d programming right_padding 600
bspc config -m $BSPWM_EXTERNALMONITOR -d programming bottom_padding 0
bspc config -m $BSPWM_EXTERNALMONITOR -d programming top_padding 0
bspc config -m $BSPWM_EXTERNALMONITOR -d programming window_gap  80

# notes
bspc config -m $BSPWM_EXTERNALMONITOR -d notes right_padding 1000
bspc config -m $BSPWM_EXTERNALMONITOR -d notes left_padding 1000

# spotify
bspc config -m $BSPWM_EXTERNALMONITOR -d spotify window_gap 0

